---
# https://copyprogramming.com/howto/ansible-ad-hoc-shell-command-quotes-inside-of-quotes
#
- name: "is {{ TheMember | quote }} a group"
  block:
  - name: check if {{ TheMember | quote }} is a group
    ansible.builtin.shell:
      cmd: 'getent group {{ TheMember | quote }}'
    register: IsItaGroup
    failed_when:
    - IsItaGroup.rc != 0
    - IsItaGroup.rc != 2
    changed_when: false

  - name: debug IsItaGroup
    ansible.builtin.debug:
      var: IsItaGroup
    when:
    - BeVerbose is defined
    - BeVerbose|bool

  - name: "if {{ TheMember }} is a group, set ItIsaGroup to true"
    ansible.builtin.set_fact:
      ItIsaGroup: true
    when: IsItaGroup.rc == 0
  when: not ItIsaUser|bool
...