---
- name: "is {{ TheMember }} a group"
  block:
  - name: check if it is a group
    ansible.builtin.shell:
      cmd: getent group '''{{ TheMember }}'''
    register: IsItaGroup
    failed_when:
    - IsItaGroup.rc != 0
    - IsItaGroup.rc != 2
    changed_when: false

  - name: debug IsItaGroup
    ansible.builtin.debug:
      var: IsItaGroup
    when:
    - BeVerbose is defined
    - BeVerbose|bool

  - name: "if {{ TheMember }} is a group, set ItIsaGroup to true"
    ansible.builtin.set_fact:
      ItIsaGroup: true
    when: IsItaGroup.rc == 0
  when: not ItIsaUser|bool
...