---
- name: realm as root
  block:
  - name: IsUser already permitted
    ansible.builtin.shell: cat /etc/sssd/sssd.conf|grep simple_allow_groups|grep -i {{ TheMember }}
    register: GroupIsAlreadyPermitted
    changed_when: false
    failed_when:
    - GroupIsAlreadyPermitted.rc != 0
    - GroupIsAlreadyPermitted.rc != 1
  
  - name: actuall permit group
    block:
    - name: debug GroupIsAlreadyPermitted
      ansible.builtin.debug:
        var: GroupIsAlreadyPermitted
      when:
      - BeVerbose is defined
      - BeVerbose|bool

    - name: permit group {{ TheMember }}
      ansible.builtin.shell: realm permit -g {{ TheMember }}
      register: PermitGroup

    - name: debug PermitGroup
      ansible.builtin.debug:
        var: PermitGroup
      when:
      - BeVerbose is defined
      - BeVerbose|bool
    when: GroupIsAlreadyPermitted.rc != 0
  become: true
  when:
  - ItIsaGroup|bool
  - TheAction == 'permit'
...